export interface NewsArticle {
  id: string;
  title: string;
  summary: string;
  topic: string;
  source: string;
  date: string;
  imageUrl: string;
  url: string;
  youtubeId?: string;
}

// Mock news data - in production, this would come from an API
export const NEWS_ARTICLES: NewsArticle[] = [
  {
    id: "1",
    title: "GPT-5 Breaks New Ground in Scientific Research",
    summary: "The latest AI model demonstrates unprecedented ability to generate novel hypotheses and design experiments across multiple scientific disciplines.",
    topic: "environment-science",
    source: "AI Research Weekly",
    date: "2026-02-08",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "2",
    title: "AI-Powered Chatbots Now Handle 80% of Customer Service",
    summary: "Major enterprises report that AI chatbots have reached human-level performance in resolving customer queries, with some surpassing human agents.",
    topic: "chatbot-development",
    source: "TechCrunch",
    date: "2026-02-08",
    imageUrl: "https://images.unsplash.com/photo-1531746790095-e5a3e0d43543?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "3",
    title: "AI Trading Systems Reshape Global Markets",
    summary: "Autonomous AI trading platforms now account for over 60% of daily trading volume, raising questions about market stability and regulation.",
    topic: "business-economy",
    source: "Financial Times",
    date: "2026-02-07",
    imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "4",
    title: "Universities Launch AI-First Curriculum Programs",
    summary: "Top universities worldwide announce comprehensive AI-integrated degree programs, fundamentally changing how subjects from humanities to engineering are taught.",
    topic: "ai-academy",
    source: "Education Today",
    date: "2026-02-07",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c476?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "5",
    title: "New AI Cybersecurity Framework Detects Zero-Day Threats",
    summary: "A revolutionary AI defense system can identify and neutralize previously unknown cyber threats in real-time, marking a paradigm shift in digital security.",
    topic: "digital-security",
    source: "CyberNews",
    date: "2026-02-07",
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "6",
    title: "AI Models Predict Climate Patterns with 99% Accuracy",
    summary: "New neural network architectures trained on decades of satellite data can now forecast extreme weather events weeks in advance.",
    topic: "environment-science",
    source: "Nature AI",
    date: "2026-02-06",
    imageUrl: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "7",
    title: "EU Passes Comprehensive AI Governance Act",
    summary: "The European Union finalizes landmark legislation establishing transparency requirements and accountability standards for AI systems deployed across member states.",
    topic: "governance-politics",
    source: "Reuters",
    date: "2026-02-06",
    imageUrl: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "8",
    title: "AI in Presidential Campaigns: The New Political Landscape",
    summary: "Political campaigns increasingly rely on AI for voter outreach, policy analysis, and debate preparation, transforming democratic processes.",
    topic: "governance-politics",
    source: "Political Wire",
    date: "2026-02-06",
    imageUrl: "https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "9",
    title: "AI Diagnostic Tools Reduce Misdiagnosis by 40%",
    summary: "Hospitals deploying AI-assisted diagnostic systems report dramatic improvements in accuracy, particularly for rare diseases and complex conditions.",
    topic: "health-style",
    source: "Medical AI Journal",
    date: "2026-02-05",
    imageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "10",
    title: "AI Fashion Designers Debut at Paris Fashion Week",
    summary: "For the first time, collections entirely designed by AI systems walk the runway at Paris Fashion Week, blending algorithmic creativity with haute couture.",
    topic: "health-style",
    source: "Vogue AI",
    date: "2026-02-05",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "11",
    title: "AI Music Composition Wins Grammy Nomination",
    summary: "An album composed entirely by AI receives its first Grammy nomination, sparking debate about creativity, authorship, and the future of music.",
    topic: "musical-art",
    source: "Rolling Stone",
    date: "2026-02-05",
    imageUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "12",
    title: "AI-Generated Art Sells for $12M at Christie's",
    summary: "A series of AI-generated artworks fetches record prices at auction, challenging traditional notions of artistic value and human creativity.",
    topic: "visual-art-photography",
    source: "ArtNet News",
    date: "2026-02-04",
    imageUrl: "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "13",
    title: "AI Photo Editing Revolutionizes Professional Photography",
    summary: "New AI-powered tools can automatically relight, recompose, and enhance photos with professional-grade results in seconds.",
    topic: "visual-art-photography",
    source: "Digital Photography Review",
    date: "2026-02-04",
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "14",
    title: "Smart Cameras with On-Device AI Transform Surveillance",
    summary: "Next-gen cameras with built-in AI chips can identify objects, track movements, and make decisions without cloud connectivity.",
    topic: "visual-art-photography",
    source: "Camera World",
    date: "2026-02-04",
    imageUrl: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "15",
    title: "Quantum-AI Hybrid Processors Hit 10,000 Qubits",
    summary: "The latest quantum-AI hybrid chips combine classical neural networks with quantum processing, opening new frontiers in computation.",
    topic: "technology-innovation",
    source: "IEEE Spectrum",
    date: "2026-02-03",
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "16",
    title: "AI Startups Raise Record $50B in Q1 2026",
    summary: "Venture capital investment in AI companies reaches new heights, with autonomous systems and enterprise AI leading funding rounds.",
    topic: "business-economy",
    source: "Bloomberg",
    date: "2026-02-03",
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "17",
    title: "Brain-Computer Interface Powered by AI Restores Speech",
    summary: "A groundbreaking AI-driven neural implant allows paralyzed patients to communicate naturally through thought-to-speech translation.",
    topic: "technology-innovation",
    source: "MIT Technology Review",
    date: "2026-02-03",
    imageUrl: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "18",
    title: "Autonomous AI Drones Complete First Urban Delivery Network",
    summary: "A fleet of AI-piloted drones successfully operates a fully autonomous delivery network across a major metropolitan area.",
    topic: "unmanned-aircraft",
    source: "DroneLife",
    date: "2026-02-02",
    imageUrl: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "19",
    title: "AI Tutors Personalize Learning for 100 Million Students",
    summary: "Adaptive AI tutoring platforms reach milestone enrollment, offering personalized curriculum that adjusts in real-time to each student's learning style.",
    topic: "ai-academy",
    source: "EdTech Magazine",
    date: "2026-02-02",
    imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "20",
    title: "AI Drug Discovery Platform Identifies New Antibiotic",
    summary: "Machine learning algorithms screen millions of molecular compounds to discover a novel antibiotic effective against drug-resistant bacteria.",
    topic: "health-style",
    source: "The Lancet",
    date: "2026-02-02",
    imageUrl: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "21",
    title: "Deepfake Detection AI Achieves 99.9% Accuracy",
    summary: "New AI models can reliably identify AI-generated content across video, audio, and images, helping combat misinformation at scale.",
    topic: "digital-security",
    source: "Wired",
    date: "2026-02-01",
    imageUrl: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "22",
    title: "AI-Designed Proteins Could Reverse Environmental Damage",
    summary: "Researchers use AI to engineer novel proteins capable of breaking down plastics and absorbing carbon at industrial scales.",
    topic: "environment-science",
    source: "Science Magazine",
    date: "2026-02-01",
    imageUrl: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "23",
    title: "Conversational AI Passes the Turing Test Consistently",
    summary: "Multiple independent evaluators confirm that leading chatbot models can no longer be reliably distinguished from human conversation partners.",
    topic: "chatbot-development",
    source: "AI Magazine",
    date: "2026-02-01",
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "24",
    title: "AI Drone Swarms Map Amazon Rainforest in Real-Time",
    summary: "Coordinated AI drone fleets create continuously updated 3D maps of the Amazon, tracking deforestation and biodiversity changes.",
    topic: "unmanned-aircraft",
    source: "National Geographic",
    date: "2026-02-01",
    imageUrl: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "25",
    title: "AI Photography App Creates Professional Portraits from Selfies",
    summary: "A new mobile app uses diffusion models to transform casual photos into studio-quality portraits with adjustable lighting and composition.",
    topic: "visual-art-photography",
    source: "PetaPixel",
    date: "2026-01-31",
    imageUrl: "https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "26",
    title: "Tech Giants Form AI Safety Coalition",
    summary: "Major technology companies announce a joint initiative to establish shared safety standards and testing protocols for frontier AI models.",
    topic: "technology-innovation",
    source: "The Verge",
    date: "2026-01-31",
    imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "27",
    title: "AI Composers Create Personalized Soundtracks for Games",
    summary: "Adaptive AI music systems generate unique, real-time soundtracks that respond to player actions and emotional states in video games.",
    topic: "musical-art",
    source: "Game Developer",
    date: "2026-01-31",
    imageUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "28",
    title: "Generative AI Transforms Architectural Design",
    summary: "Architects use AI to generate building designs that optimize for sustainability, cost, and aesthetics simultaneously, reducing design time by 90%.",
    topic: "technology-innovation",
    source: "Architectural Digest",
    date: "2026-01-30",
    imageUrl: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "29",
    title: "AI Art Tools Spark Renaissance in Digital Creativity",
    summary: "Democratization of AI art tools leads to an explosion of creative output, with millions of new artists exploring AI-assisted creation.",
    topic: "visual-art-photography",
    source: "Creative Bloq",
    date: "2026-01-30",
    imageUrl: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=600&h=400&fit=crop",
    url: "#",
  },
  {
    id: "30",
    title: "AI-Powered Smart Cameras Revolutionize Wildlife Conservation",
    summary: "Camera traps with edge AI automatically identify and track endangered species, providing real-time biodiversity monitoring at scale.",
    topic: "visual-art-photography",
    source: "Conservation Tech",
    date: "2026-01-30",
    imageUrl: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef3?w=600&h=400&fit=crop",
    url: "#",
  },
];

export function getNewsByTopics(topicIds: string[]): NewsArticle[] {
  if (topicIds.length === 0) return NEWS_ARTICLES;
  return NEWS_ARTICLES.filter((article) => topicIds.includes(article.topic));
}

export function searchNews(query: string): NewsArticle[] {
  const q = query.toLowerCase();
  return NEWS_ARTICLES.filter(
    (article) =>
      article.title.toLowerCase().includes(q) ||
      article.summary.toLowerCase().includes(q) ||
      article.topic.toLowerCase().includes(q)
  );
}
